// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjdssoyudnszczxdkenj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqZHNzb3l1ZG5zemN6eGRrZW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzU1NzEsImV4cCI6MjA2NDExMTU3MX0.1bYqeD3g24avXYJ6TdGtloViiZjKnAGDqAQJU534jzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);